import { readFileSync } from 'node:fs';
import { join, matchesGlob } from 'node:path';

// Regression guard for #64: the published npm tarball must contain the
// compiled Expo config plugin (`plugin/build/index.js`) that `app.plugin.js`
// `require()`s. v0.4.0 shipped `app.plugin.js` but NOT `plugin/build/`, so
// every Expo app that listed the package in its `plugins` array crashed at
// config-resolution time with "Cannot find module './plugin/build'".
//
// Root cause: `plugin/build` is gitignored and regenerated by `prepack`, then
// shipped via the package.json `files` allowlist. A bare `"plugin/build"`
// entry is honored by `npm pack` but dropped by `yarn pack` — Yarn 4
// auto-recurses only single-segment top-level dirs (`lib`, `nitrogen`), not
// nested ones, so the *contents* of `plugin/build` were excluded. v0.4.0 was
// packed with Yarn, hence the missing directory. The fix is the recursive glob
// `"plugin/build/**"`, which both packers honor. These assertions fail if
// anyone reverts to the non-recursive form or breaks the require/build wiring.

const pkgDir = join(__dirname, '..');

interface PkgJson {
  files: string[];
  scripts: Record<string, string>;
}

const pkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')) as PkgJson;

// The compiled entry `app.plugin.js` resolves to, kept in lockstep with
// `plugin/tsconfig.json` (rootDir `src`, outDir `build`) and `app.plugin.js`.
const PLUGIN_ENTRY = 'plugin/build/index.js';

// Model the package.json `files` allowlist: a relative path ships iff some
// positive glob matches it and no negative (`!`-prefixed) glob excludes it.
function isPacked(relPath: string, files: string[]): boolean {
  const positives = files.filter((f) => !f.startsWith('!'));
  const negatives = files.filter((f) => f.startsWith('!')).map((f) => f.slice(1));
  const included = positives.some((g) => matchesGlob(relPath, g));
  const excluded = negatives.some((g) => matchesGlob(relPath, g));
  return included && !excluded;
}

describe('Expo config plugin packaging (#64)', () => {
  it('app.plugin.js requires the compiled ./plugin/build entry', () => {
    const src = readFileSync(join(pkgDir, 'app.plugin.js'), 'utf8');
    expect(src).toMatch(/require\(['"]\.\/plugin\/build['"]\)/);
  });

  it('the files allowlist matches the compiled plugin entry as a FILE, not just the directory', () => {
    // The crux of #64: a bare `plugin/build` matches the *directory* but not a
    // file path *under* it, which is exactly why `yarn pack` dropped the
    // contents. Pin that distinction so a regression to the bare form fails.
    expect(matchesGlob(PLUGIN_ENTRY, 'plugin/build')).toBe(false);
    expect(isPacked(PLUGIN_ENTRY, pkg.files)).toBe(true);
  });

  it('ships app.plugin.js itself', () => {
    expect(isPacked('app.plugin.js', pkg.files)).toBe(true);
  });

  it('prepack regenerates the compiled plugin before packing', () => {
    // `plugin/build` is gitignored, so the tarball is only correct if prepack
    // rebuilds it. Guard the build wiring alongside the allowlist.
    expect(pkg.scripts.prepack).toMatch(/build:plugin/);
    expect(pkg.scripts['build:plugin']).toBeDefined();
  });
});
