// Expo resolves this file when a consumer adds 'react-native-video-pipeline'
// to the `plugins` array in app.json / app.config.{js,ts}. It re-exports the
// compiled config plugin from plugin/build (generated by `yarn build:plugin`,
// shipped in the npm tarball, gitignored).
module.exports = require('./plugin/build');
